server:
  port: 8765

spring:
  application:
    name: hystrix-turbine-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.198.1:8761/eureka/

turbine:
  instanceUrlSuffix: /hystrix.stream
  aggregator:
    clusterConfig: default
  appConfig: say-hello-service
  clusterNameExpression: new String("default")

