server:
  port: 8762

spring:
  application:
    name: say-hello-service
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.198.1:8761/eureka/


