server:
  port: 8766

spring:
  application:
    name: zuul-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    say-hello-service:
      path: /say-hello-service/**
      serviceId: say-hello-service
    greeting-service:
      path: /greeting-service/**
      serviceId: greeting-service