server:
  port: 8764

spring:
  application:
    name: greeting-service
  zipkin:
    base-url: http://192.168.198.1:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.198.1:8761/eureka/

feign:
  hystrix:
    enabled: true



