server:
  port: 8761
# Spring Cloud 2.0 配置
spring:
  application:
    name: eureka-server
  security:
    basic:
      enabled: true # 开启安全配置，需要密码，必须放在 application.yml 中，不可以放在 bootstrap.yml 中。
    user:
      name: admin
      password: 123456 # 配置了用户名和密码后，可以修改地址的访问风格为 curl 风格
eureka:
  instance:
    hostname: 192.168.198.1
  client:
    registerWithEureka: false # 由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
    fetchRegistry: false # 由于注册中心的职责就是维护服务示例,它并不需要去检索服务,所以也设置为false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/



