server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.198.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

security:
  user:
    name:


